spring:
  datasource:
    url: jdbc:postgresql://postgres-product-dev:5432/productdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/dev
    baseline-on-migrate: true
    validate-on-migrate: true

user:
  service:
    url: http://user-service-dev:8081
