# ============================================
# USER SERVICE URL  - DEV PROFILE
# ============================================
spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/productdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

flyway:
  enabled: true
  locations: classpath:db/migration/dev
  baseline-on-migrate: true
  validate-on-migrate: true

user:
  service:
    url: http://user-service-dev:8081